import torch
import os

import numpy as np
from tqdm import tqdm

from models.transformer import Transformer
from dataset import EncodedImageDataset
import argparse
import yaml

from scheduler import linear_schedule


"""

"""
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint_dir", type = str, help = "path to directory with checkpoint", required = True)
    parser.add_argument("--checkpoint", type = str, required = True)
    parser.add_argument("--test_dataset", type = str, help = "path to .pt file of preprocessed images (generated by transformer_preprocessing.py)")
    args = parser.parse_args()

    with open(os.path.join("checkpoints", args.checkpoint_dir, "config.yaml")) as f:
        config = yaml.safe_load(f)

    if torch.cuda.is_available:
        device = 'cuda'
    else:
        device = 'cpu'
        raise RuntimeWarning("Failed to detect CUDA capable GPU; defaulting to CPU")

    data = EncodedImageDataset(args.test_dataset)
    dataloader = torch.utils.data.Dataloader(
        data,
        batch_size = 32,
        shuffle = False,
        num_workers = 8,
        pin_memory = True
    )

    model = Transformer(config)
    model.load_checkpoint(os.path.join("checkpoints", args.checkpoint_dir, args.checkpoint))

    model.eval()

    batch_iter = tqdm(dataloader,  leave=True)

    for batch in batch_iter:
        batch = batch.to(device, non_blocking=True).long() # Cast to long here because idx were saved as smaller data
        cur_batch_size = batch.size(0)

        input_ids, labels = mask_inputs(
            batch,
            self.mask_token_id,
            self.mask_scheduler,
            ignore_index=-100,
        )

        assert not (labels == -100).all(), f"Batch is entirely unmasked. Check masking logic. {labels[labels != -100].shape, labels[labels == -100].shape}"

        logits = self.model(input_ids)
        loss = self.criterion(
            logits.view(-1, logits.size(-1)), # B * L, classes view
            labels.view(-1), # B * L, index is class
        )

        total_epoch_loss += loss.item() * cur_batch_size
        num_steps += cur_batch_size
        avg_loss = total_epoch_loss / num_steps

        # Write average loss so far to progress bar
        batch_iter.set_postfix({'avg_loss': f"{avg_loss:.4f}"})

        self.optimizer.zero_grad(set_to_none=True)
        loss.backward()
        self.optimizer.step()

    assert num_steps > 0
    avg_epoch_loss = total_epoch_loss / num_steps
    self.save_checkpoint(epoch, avg_epoch_loss)



if __name__ == "__main__":
    main()